import React from "react";
import Pixel from "./Pixel";

class App extends React.Component {
  constructor(props) {
    super(props);

    // this.state = {
    // backgroundColor: 'green'
    // }
  }

  render() {
    return Array.from({ length: 100 }, (_, i) => <Pixel key={i} />);
  }
}

// render() {
//   return (
//     <div>
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel /> <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//       <Pixel />
//     </div>
//   );
// }

export default App;
